'use strict';

const fs = require('fs');
const path = require('path');
const { createEnvelope, DEFAULT_RETRY_POLICIES } = require('../../engine/tool-interface');

const SAFE_PREFIXES = ['/Users/vineet/', '/tmp/'];

module.exports = {
  name: 'plan_creator',
  description: 'Create structured markdown implementation plans from a brief. Returns plan content for in-chat use or writes to a file path.',
  inputSchema: {
    type: 'object',
    properties: {
      title: { type: 'string', description: 'Plan title' },
      description: { type: 'string', description: 'What needs to be planned' },
      constraints: { type: 'string', description: 'Optional constraints or requirements' },
      outputPath: { type: 'string', description: 'Optional file path to write the plan to' },
    },
    required: ['title', 'description'],
  },
  permissionTier: 'confirm',
  category: 'create',
  timeout: 60000,
  retryPolicy: DEFAULT_RETRY_POLICIES.create,

  async execute(input) {
    const start = Date.now();
    const meta = { tool: 'plan_creator', duration_ms: 0, attempt: 1, truncated: false, cost_usd: 0 };

    try {
      const { title, description, constraints, outputPath } = input;

      if (!title || typeof title !== 'string') {
        meta.duration_ms = Date.now() - start;
        return createEnvelope(false, null, 'title is required and must be a string', meta);
      }
      if (!description || typeof description !== 'string') {
        meta.duration_ms = Date.now() - start;
        return createEnvelope(false, null, 'description is required and must be a string', meta);
      }

      const plan = [
        `# ${title}`,
        '',
        '## Overview',
        description,
        '',
        '## Constraints',
        constraints || 'None specified',
        '',
        '## Tasks',
        '- [ ] Task 1: Analyze requirements',
        '- [ ] Task 2: Design solution',
        '- [ ] Task 3: Implement',
        '- [ ] Task 4: Test',
        '- [ ] Task 5: Deploy',
        '',
        '## Notes',
        'Generated by Lucy v3 plan_creator tool',
        `Created: ${new Date().toISOString()}`,
        '',
      ].join('\n');

      const result = { plan };

      if (outputPath) {
        const resolved = path.resolve(outputPath);
        const isSafe = SAFE_PREFIXES.some(prefix => resolved.startsWith(prefix));
        if (!isSafe) {
          meta.duration_ms = Date.now() - start;
          return createEnvelope(false, null, `Unsafe output path: ${resolved}. Must be under ${SAFE_PREFIXES.join(' or ')}`, meta);
        }

        const dir = path.dirname(resolved);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        fs.writeFileSync(resolved, plan, 'utf8');
        result.path = resolved;
      }

      meta.duration_ms = Date.now() - start;
      return createEnvelope(true, result, null, meta);
    } catch (err) {
      meta.duration_ms = Date.now() - start;
      return createEnvelope(false, null, err.message, meta);
    }
  },
};
