'use strict';

const fs = require('fs');
const path = require('path');

describe('plan_creator tool', () => {
  let tool;

  beforeEach(() => {
    vi.resetModules();
    tool = require('../../src/tools/v2/plan-creator.tool.js');
  });

  afterEach(() => {
    // Clean up any test files
    const testFile = '/tmp/plan-creator-test-output.md';
    if (fs.existsSync(testFile)) {
      fs.unlinkSync(testFile);
    }
  });

  it('generates valid markdown plan', async () => {
    const result = await tool.execute({
      title: 'Test Plan',
      description: 'Build a test feature',
    });
    expect(result.ok).toBe(true);
    expect(result.data.plan).toContain('# Test Plan');
    expect(result.data.plan).toContain('## Overview');
    expect(result.data.plan).toContain('## Tasks');
    expect(result.data.plan).toContain('- [ ] Task 1');
    expect(result.data.plan).toContain('Generated by Lucy v3 plan_creator tool');
    expect(result.data.plan).toContain('Created:');
  });

  it('includes title and description in output', async () => {
    const result = await tool.execute({
      title: 'My Feature Plan',
      description: 'Implement user authentication with JWT tokens',
    });
    expect(result.ok).toBe(true);
    expect(result.data.plan).toContain('# My Feature Plan');
    expect(result.data.plan).toContain('Implement user authentication with JWT tokens');
  });

  it('writes to outputPath when provided', async () => {
    const testPath = '/tmp/plan-creator-test-output.md';
    const result = await tool.execute({
      title: 'File Plan',
      description: 'A plan written to disk',
      outputPath: testPath,
    });
    expect(result.ok).toBe(true);
    expect(result.data.path).toBe(testPath);
    expect(fs.existsSync(testPath)).toBe(true);
    const content = fs.readFileSync(testPath, 'utf8');
    expect(content).toContain('# File Plan');
  });

  it('rejects unsafe outputPath', async () => {
    const result = await tool.execute({
      title: 'Evil Plan',
      description: 'Should not work',
      outputPath: '/etc/something.md',
    });
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/Unsafe output path/);
  });

  it('handles missing optional fields', async () => {
    const result = await tool.execute({
      title: 'Minimal Plan',
      description: 'Just title and description',
    });
    expect(result.ok).toBe(true);
    expect(result.data.plan).toContain('## Constraints');
    expect(result.data.plan).toContain('None specified');
    expect(result.data.path).toBeUndefined();
  });

  it('includes constraints when provided', async () => {
    const result = await tool.execute({
      title: 'Constrained Plan',
      description: 'A feature',
      constraints: 'Must be done by Friday',
    });
    expect(result.ok).toBe(true);
    expect(result.data.plan).toContain('Must be done by Friday');
  });

  it('returns proper envelope metadata', async () => {
    const result = await tool.execute({
      title: 'Meta Plan',
      description: 'Check metadata',
    });
    expect(result.metadata.tool).toBe('plan_creator');
    expect(typeof result.metadata.duration_ms).toBe('number');
    expect(result.metadata.truncated).toBe(false);
    expect(result.metadata.cost_usd).toBe(0);
  });

  it('rejects missing title', async () => {
    const result = await tool.execute({
      description: 'No title provided',
    });
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/title/i);
  });

  it('rejects missing description', async () => {
    const result = await tool.execute({
      title: 'No Description',
    });
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/description/i);
  });
});
